### ISSUE TITLE
DynamoDB query operation missing data

### ISSUE THREAD

**Issue by davidgasquez** [paws-r/paws#244]
Hey there! We've recently started to use this library to run a few operations on DynamoDB. We encountered a strange bug a few days ago. The data structure we have is something like this:

```json
{
  "HourMap": {
    "M": {
      "22": {
        "N": "142"
      },
      "23": {
        "N": "121"
      },
      "10": {
        "N": "270"
      },
      "11": {
        "N": "265"
      },
      "12": {
        "N": "276"
      },
      "13": {
        "N": "263"
      },
      "14": {
        "N": "262"
      },
      "15": {
        "N": "244"
      },
      "16": {
        "N": "235"
      },
      "17": {
        "N": "225"
      },
      "18": {
        "N": "213"
      },
      "19": {
        "N": "229"
      },
      "0": {
        "N": "141"
      },
      "1": {
        "N": "140"
      },
      "2": {
        "N": "132"
      },
      "3": {
        "N": "142"
      },
      "4": {
        "N": "177"
      },
      "5": {
        "N": "210"
      },
      "6": {
        "N": "243"
      },
      "7": {
        "N": "254"
      },
      "8": {
        "N": "267"
      },
      "9": {
        "N": "270"
      },
      "20": {
        "N": "185"
      },
      "21": {
        "N": "160"
      }
    }
  },
  "UserId": {
    "S": "17841401828740000"
  },
  "Day": {
    "S": "2020-02-02T08:00:00+0000"
}
```

The `HourMap` field is a map of each hour of the day to a number. The DynamoDB query looks like this:

```R
svc$query(
    ExpressionAttributeNames = list(
        `#DA` = "Day"
    ),
    ExpressionAttributeValues = list(
        `:u` = list(
        S = my_user_id
        ),
        `:d` = list(
        S = "2020-02-02"
        )
    ),
    KeyConditionExpression = "UserId = :u AND #DA > :d",
    TableName = "my-dynamodb-table"
)
```

Running that query will return something strange:

```json
{
  "UserId": {
    "S": "12345",
    "N": [],
    "B": [],
    "SS": [],
    "NS": [],
    "BS": [],
    "M": [],
    "L": [],
    "NULL": [],
    "BOOL": []
  },
  "Day": {
    "S": "2020-02-02T08:00:00+0000",
    "N": [],
    "B": [],
    "SS": [],
    "NS": [],
    "BS": [],
    "M": [],
    "L": [],
    "NULL": [],
    "BOOL": []
  },
  "HourMap": {
    "S": [],
    "N": [],
    "B": [],
    "SS": [],
    "NS": [],
    "BS": [],
    "M": {
      "22": [],
      "23": [],
      "10": [],
      "11": [],
      "12": [],
      "13": [],
      "14": [],
      "15": [],
      "16": [],
      "17": [],
      "18": [],
      "19": [],
      "0": [],
      "1": [],
      "2": [],
      "3": [],
      "4": [],
      "5": [],
      "6": [],
      "7": [],
      "8": [],
      "9": [],
      "20": [],
      "21": []
    },
    "L": [],
    "NULL": [],
    "BOOL": []
  }
}
```

Doing the same query with [Python's `boto3`](https://boto3.amazonaws.com/v1/documentation/api/latest/index.html) or with the `aws` command line interface¹ returns the right data. 

**Could this be related with a malformed request from `paws` on the [`query` operation](https://github.com/paws-r/paws/blob/master/paws/R/dynamodb_operations.R#L3053-L3068)?**

¹ This is the query we used in the `aws` CLI to get the data.

```bash
$ aws dynamodb query \
    --table-name "my-dynamodb-table" \
    --key-condition-expression "UserId = :u AND #DA > :d" \
    --expression-attribute-names '{"#DA": "Day"}' \
    --expression-attribute-values  '{":u":{"S":"12345"}, ":d": {"S":"2020-02-02"}}'
```

**Comment by davidkretch** [comment]
That is definitely weird and bad.  We will look at it as soon as possible -- in the next few days.  Thank you!

**Comment by davidgasquez** [comment]
Thanks a lot @davidkretch! Let me know if I you need anything else for debugging or validating purposes.

Not sure if related with this one, but we're also having issues with `update_item` when updating with list (`L`) type or map (`M`) type. The following code will fail:


```r
svc$update_item(
    ExpressionAttributeNames = list(
        `#FTU` = "FieldToUpdate"
    ),
    ExpressionAttributeValues = list(
        `:ftu` = list(
        L = list(
            list(S = "Cookies"),
            list(S = "Coffee")
            )
        )
    ),
    Key = list(
        UserId = list(
        S = my_user_id
        )
    ),
    UpdateExpression = "SET #FTU = :ftu",
    TableName = "my-dynamodb-table"
)
```

If we switch the data type of `:ftu` in `ExpressionAttributeValues` to `S = "Cookies"` it works. 

We would want to add data with this structure:

```json
[
  {
    "M": {
      "Hour": {
        "S": "1"
      },
      "Prediction": {
        "N": "100"
      }
    }
  },
  {
    "M": {
      "Hour": {
        "S": "2"
      },
      "Prediction": {
        "N": "200"
      }
    }
  }
]
```

Using that JSON with `aws dynamodb update-item ....` works. Loading it into R and running the `svc$update_item` returns an error related with the name of the map items, in this case `"Error in populate_fn(input, interface) : invalid name: Hour`.

**Comment by davidkretch** [comment]
Thanks for the update!  We'll also take a look at that.

**Comment by davidkretch** [comment]
Hello again.  Sorry this functionality did not work.  I believe we have a fix on master, and we're going to try to get it on CRAN by some time next week.

You can try it by installing the latest `paws.common` with:

```
devtools::install_github("paws-r/paws/paws.common")
```

If you do try it, please let us know if you have issues.  Thank you!

**Comment by davidkretch** [comment]
The latest version of paws.common is on CRAN and should fix this.  Thank you!

**Comment by davidgasquez** [comment]
Thanks for working on this so quickly! It seems the fix worked for the `query` but we're still having issues with `update_item` and can't update `Map` or `List` items. 

I don't have the logs at hand right now, but we'll get back to you after updating everything again and running that command later today.

**Comment by davidgasquez** [comment]
This is the code to update a field:

```R
svc$update_item(
    ExpressionAttributeNames = list(
        `#FTU` = "FieldToUpdate"
    ),
    ExpressionAttributeValues = list(
        `:ftu` = list(
        L = list(
            list(S = "Cookies"),
            list(S = "Coffee")
            )
        )
    ),
    Key = list(
        UserId = list(
        S = my_user_id
        )
    ),
    UpdateExpression = "SET #FTU = :ftu",
    TableName = "my-dynamodb-table"
)
```

Running that will return this: `Error: com.amazon.coral.validate: Invalid UpdateExpression: An expression attribute value used in expression is not defined; attribute value: :ftu`

**Comment by davidkretch** [comment]
Nuts.  This one is hard.  I tried it in one Windows and one Linux environment where it seemed to work.  Can you post your sessionInfo?

**Comment by davidgasquez** [comment]
We tried again with the example data and it worked. When we were translating the data structure I mentioned in https://github.com/paws-r/paws/issues/244#issuecomment-585619785, we made a mistake and that was the cause of the error. 

This is the data structure:
```json
[
  {
    "M": {
      "Hour": {
        "S": "1"
      },
      "Prediction": {
        "N": "100"
      }
    }
  },
  {
    "M": {
      "Hour": {
        "S": "2"
      },
      "Prediction": {
        "N": "200"
      }
    }
  }
]
```

And this is how the `ExpressionAttributeValues` parameter looks:

```R
L = list(
list(M = list("Hour" = list(N = 1), "Prediction" = list(N = 100))),
list(M = list("Hour" = list(N = 2), "Prediction" = list(N = 200)))
)
```

I think all is working now on our end. I appreciate a lot your help! Thanks for bearing with me through this issue. :raised_hands:

**Comment by davidkretch** [comment]
Excellent!  Thank you for pointing out this bug.  I'm glad we got it sorted out.
